from .math_ops.op_cos import derivative_cos
from .math_ops.op_exp import derivative_exp
from .math_ops.op_log import derivative_log
from .math_ops.op_relu import derivative_relu
from .math_ops.op_sigmoid import derivative_sigmoid
from .math_ops.op_sin import derivative_sin
from .math_ops.op_softmax import derivative_softmax
from .math_ops.op_tan import derivative_tan
from .math_ops.op_tanh import derivative_tanh
